:server:
  :ip: localhost
  :domain: cacique.mercadolibre.com
    
:db:
  :production:
    :adapter: mysql
    :encoding: utf8
    :name: cacique
    :pool: 5
    :username: cacique
    :password: cacique
    :host: localhost
    :port: 3306
  :development:
    :adapter: mysql
    :encoding: utf8
    :name: cacique_dev
    :pool: 5
    :username: cacique
    :password: cacique
    :host: localhost
    :port: 3306
  :test:
    :adapter: mysql
    :encoding: utf8
    :name: cacique_test
    :pool: 5
    :username: cacique
    :password: cacique
    :host: localhost
    :port: 3306
    
:memcached:
  :ip: localhost
    
:starling:
  :ip: localhost
  :port: 22122
    
:mannager:
  :ip: localhost
  :port: 33133
    
:hub:
  :ip: localhost
  :port: 4444
  :end: "/"

:webdriverdhub:
  :ip: localhost
  :port: 5555
