#   SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)


development:
  adapter: mysql
  encoding: utf8
  database: cacique_dev
  pool: 5
  username: cacique
  password: cacique
  host: localhost
  port: 3306

test:
  adapter: mysql
  encoding: utf8
  database: cacique_test
  pool: 5
  username: cacique
  password: cacique
  host: localhost
  port: 3306

production:
  adapter: mysql
  encoding: utf8
  database: cacique
  pool: 5
  username: cacique
  password: cacique
  host: localhost
  port: 3306
