#!/bin/bash
case "$1" in
  start)
        cd /home/cacique/cacique/extras/selenium-grid2.0rc3
        exec nohup java -jar selenium-server-standalone-2.0rc3.jar -role hub > /dev/NULL &
	pgrep -f selenium-server > /tmp/hub.pid
  ;;
  stop)
	rm /tmp/hub.pid
	kill `pgrep -f selenium-server`
  ;;
esac


