#!/bin/bash
case "$1" in
  start)
        cd /home/juan/Desktop/CACIQUE_GITHUB/cacique
        exec script/mannager.rb > /dev/null &
        pgrep -f mann > /home/juan/Desktop/CACIQUE_GITHUB/cacique/log/task_manager.pid
  ;;
  stop)
        rm /home/juan/Desktop/CACIQUE_GITHUB/cacique/log/task_manager.pid
        kill `pgrep -f mann`
  ;;
esac
