#!/bin/bash
case "$1" in
  start)
        cd 
        exec script/mannager.rb > /dev/null &
        pgrep -f mann > cacique/log/task_manager.pid
  ;;
  stop)
        rm cacique/log/task_manager.pid
        kill `pgrep -f mann`
  ;;
esac
