#!/bin/bash
case "$1" in
  start)
     exec /home/juan/Desktop/CACIQUE_GITHUB/cacique/script/starling.rb -h 10.10.35.34 >  /dev/null &
  ;;
  stop)
     exec /bin/kill `/bin/cat /var/run/starling.pid`
  ;;
esac
